import numpy as np
from numpy.typing import NDArray
from track_funcs import Defaults
from typing import List, Callable, Dict, Any
from notes import NoteEvent

type TrackData = NDArray[np.float64]
type NoteData = NDArray[np.float64]


class Track:
    track_len: int = 0  # The number of notes
    track_time: float = 0.0  # Time in seconds
    sample_rate: int = (
        48000  # Standard sample rates: 44100, 48000, 88200, 96000, 192000
    )
    _notes: List[NoteEvent] = []  # The list of notes added
    _funcs: Dict[str, Callable] = {}
    opts: Dict[str, Any] = {}

    def __init__(
        self,
        sample_rate: int = 48000,
        track_time: int = 0,
        default_class: type = Defaults,
    ) -> None:
        self.sample_rate = sample_rate
        self.track_time = track_time
        self.set_default_funcs(default_class)

    def add(self, note: NoteEvent) -> None:
        self._notes.append(note)
        self.track_len += 1

        self.track_time = max(note.stop, self.track_time)

    def add_note(
        self, freq: float, start: float, stop: float, volume: float = 1.0, **kwargs
    ) -> None:
        """
        Convenience function for `Track.add()`

        `Track.add()` requires a `NoteEvent` as the parameter. This function just builds a `NoteEvent` with the provided data
        """
        self.add(NoteEvent(freq, start, stop, volume, kwargs))

    def reset(self) -> None:
        self.track_len = 0
        self.track_time = 0.0
        self._notes = []

    def set_func(self, func_name: str, func: Callable) -> None:
        """
        Adds or modifies the given function to the Track functions
        """
        self._funcs[func_name] = func

    def set_default_funcs(self, default_class: type = Defaults) -> None:
        """
        Sets the Track functions to those defined in 'default_class'

        Existing functions with the same name will be overwritten. All others will remain.
        """
        for base_cls in default_class.__mro__:
            for name, value in vars(base_cls).items():
                if isinstance(value, staticmethod):
                    self.set_func(name, value.__func__)

    def call_func(self, func_name: str, *args, **kwargs) -> Any:
        try:
            func = self._funcs[func_name]
        except KeyError:
            raise NameError(
                f"Function '{func_name}' is not defined in the Track functions. "
                f"Try adding it with 'Track.add_func(\"{func_name}\", my_function)'"
            ) from None

        return func(self, *args, **kwargs)

    def get_track_size(self) -> int:
        """
        Get the length of the generated track

        The track size is generated by multiplying the track time (in seconds) and the sample rate (in Hz)

        Returns:
        `int`: The actual length of the generated track
        """
        return int(self.track_time * self.sample_rate)

    def generate_raw_track(self) -> TrackData:
        """
        Generate and return the actual track as a float array

        Float arrays allows preserving data beyond the -1.0 and 1.0 clamping. However, when actually playing float audio, anything above 1.0 or below -1.0 will get cut off. For the actual final export, using `Track.generate_track()` to generate a in16 array is generally better.

        Returns:
        `TrackData`: The generated track as a float64 array
        """
        return self.call_func("generate")

    def generate_track(self) -> np.typing.NDArray[np.int16]:
        """
        Generate and return the actual track as an int16 array

        16 bit audio (int16) is the standard for the final export. If you want the track as a float (float64), use `Track.generate_raw_track()`.

        Returns:
        `NDArray[numpy.int16]`: The generated track as a int16 array
        """

        return (np.clip(self.generate_raw_track(), -1.0, 1.0) * 32767).astype(np.int16)
